{% set version = "4.0.0" %}
{% set cov_fail_under = 76 %}
{% set test_skips = "not (simple or data_file_filter or data_os_filter)" %}
{% set min_python = "python >=3.8" %}

package:
  name: cyclonedx-bom
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-bom/cyclonedx_bom-{{ version }}.tar.gz
    sha256: 937253800a416e5e40dda3c9f07247624b00fe6f9ea7d31c78a7f00585d054ab
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 9461552f4b4551f2e3f8f37ff48a8d915f6edf2f4a74f3f4e91622ccd73e99fd

build:
  number: 0
  noarch: python
  entry_points:
    - cyclonedx-py = cyclonedx_py._internal.cli:run
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - {{ PYTHON }} -c "import site, pathlib; sp = pathlib.Path(site.getsitepackages()[0]); [(sp / p).unlink() for p in ['LICENSE', 'NOTICE']]"

requirements:
  host:
    - {{ min_python }}
    - pip
    - poetry-core >=1.0.0
  run:
    - {{ min_python }}
    - chardet >=5.1.0,<6.0.0
    - cyclonedx-python-lib >=6.1.0,<7.0.0
    - cyclonedx-python-lib-with-validation
    - packageurl-python >=0.11,<2
    - packaging >=22.0.0,<23.0.0
    - pip-requirements-parser >=32.0.0,<33.0.0
    - tomli >=2.0.1,<3.0.0

test:
  source_files:
    - src/tests
  requires:
    - coverage
    - ddt
    - pip
    - pytest
  imports:
    - cyclonedx_py
  commands:
    - pip check
    - cyclonedx-py --help

    - >
      cd src
      && python -c "__import__('pathlib').Path('tests/integration/test_cli_environment.py').unlink()"
      && coverage run --source cyclonedx_py --branch -m pytest -vv --color=yes --tb=long -k "{{ test_skips }}"
    - coverage report --show-missing --skip-covered --fail-under={{ cov_fail_under }}

about:
  home: https://github.com/CycloneDX/cyclonedx-python
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE

extra:
  recipe-maintainers:
    - bollwyvl
