{% set version = "3.2.2" %}
{% set cov_fail_under = 47 %}
{% set test_skips = "not test_simple" %}

package:
  name: cyclonedx-bom
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-bom/cyclonedx-bom-{{ version }}.tar.gz
    sha256: f600ecef111ef2036dada7ce786896aded8bacceb51672c2db98e106e36cf1a6
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: fda925c11737499eaa3df916bed23cc9989c6d1afb9301d736925e7833455ce0

build:
  number: 0
  noarch: python
  entry_points:
    - cyclonedx-bom = cyclonedx_py.client:main
    - cyclonedx-py = cyclonedx_py.client:main
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - cyclonedx-python-lib >=2.0.0,<3.0.0
    - importlib-metadata >=3.4
    - packageurl-python >=0.9
    - pip-requirements-parser >=31.2.0,<32.0.0
    - python >=3.6
    - setuptools >=47.0.0
    - toml >=0.10.0,<0.11.0

test:
  source_files:
    - src/tests
  requires:
    - pip
    - pytest-cov
  imports:
    - cyclonedx_py
  commands:
    - pip check
    - cyclonedx-bom --help
    - cyclonedx-py --help
    - pytest src/tests -vv --cov cyclonedx_py --cov-report term-missing:skip-covered --no-cov-on-fail -k "{{ test_skips }}" --cov-fail-under {{ cov_fail_under }}

about:
  home: https://github.com/CycloneDX/cyclonedx-python
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE

extra:
  recipe-maintainers:
    - bollwyvl
