{% set version = "4.1.3" %}
{% set min_python = "python >=3.8" %}

package:
  name: cyclonedx-bom
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-bom/cyclonedx_bom-{{ version }}.tar.gz
    sha256: 711af4ee920e2a0f5403dfd6e034f681c43dd41b8ab7e25109a847e309b9c9d1
  # pypi sdist does not include all test data
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 71f983eb96e2a4b4d97463398d144222882ffda20beaa27ecd8f6088e8bb5225

build:
  number: 0
  noarch: python
  entry_points:
    - cyclonedx-py = cyclonedx_py._internal.cli:run
  script:
    - cd src && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - {{ PYTHON }} -c "import site, pathlib; sp = pathlib.Path(site.getsitepackages()[0]); assert not all((sp / p).exists() for p in ['LICENSE', 'NOTICE']);"

requirements:
  host:
    - {{ min_python }}
    - pip
    - poetry-core >=1.0.0
  run:
    - {{ min_python }}
    - chardet >=5.1,<6.0
    - cyclonedx-python-lib >=6.1.0,<7.0.0
    - cyclonedx-python-lib-with-validation
    - packageurl-python >=0.11,<2
    - packaging >=22.0.0,<24.0.0
    - pip-requirements-parser >=32.0,<33.0
    - tomli >=2.0.1,<3.0.0

test:
  source_files:
    - src/tests
  requires:
    - coverage
    - ddt
    - pip
    - pytest
  imports:
    - cyclonedx_py
  commands:
    - pip check
    - cyclonedx-py --help
    - python -c "__import__('pathlib').Path('src/tests/integration/test_cli_environment.py').unlink()"
    - coverage run --source cyclonedx_py --branch -m pytest src/tests -vv --color=yes --tb=long -k "not ( simple or data_file_filter or data_os_filter )"
    - coverage report --show-missing --skip-covered --fail-under=77

about:
  home: https://github.com/CycloneDX/cyclonedx-python
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE

extra:
  recipe-maintainers:
    - bollwyvl
