{% set version = "3.1.0" %}
{% set cov_fail_under = 47 %}
{% set test_skips = "not test_simple" %}

package:
  name: cyclonedx-bom
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-bom/cyclonedx-bom-{{ version }}.tar.gz
    sha256: 93e53241981b2a002f6c48f6234e2fbc58ef8c4b71bf5859778841e83c1d227f
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: cdd12ece5a0ba37e676a304ec4aeeff47d358f09bd1d8405321db620dcb275a4

build:
  number: 0
  noarch: python
  entry_points:
    - cyclonedx-bom = cyclonedx_py.client:main
    - cyclonedx-py = cyclonedx_py.client:main
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - cyclonedx-python-lib >=2.0.0,<3.0.0
    - pip-requirements-parser >=31.2.0,<32.0.0
    - python >=3.6

test:
  source_files:
    - src/tests
  requires:
    - pip
    - pytest-cov
  imports:
    - cyclonedx_py
  commands:
    - pip check
    - cyclonedx-bom --help
    - cyclonedx-py --help
    - pytest src/tests -vv --cov cyclonedx_py --cov-report term-missing:skip-covered --no-cov-on-fail -k "{{ test_skips }}" --cov-fail-under {{ cov_fail_under }}

about:
  home: https://github.com/CycloneDX/cyclonedx-python
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE

extra:
  recipe-maintainers:
    - bollwyvl
