{% set version = "2.0.2" %}
{% set cov_fail_under = 47 %}
{% set test_skips = "not test_simple" %}

package:
  name: cyclonedx-bom
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-bom/cyclonedx-bom-{{ version }}.tar.gz
    sha256: 319f5431153f9b063884bb2a448bcb93bcc1f42d4ac1f7fd0c0dcbfd614013dc
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 7dd4b15afdc767fa429b23873be4ab5fb3281b2d08b2286828207e2ed54b1748

build:
  number: 0
  noarch: python
  entry_points:
    - cyclonedx-bom = cyclonedx_py.client:main
    - cyclonedx-py = cyclonedx_py.client:main
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - cyclonedx-python-lib >=1.3.0,<2.0.0
    - python >=3.6

test:
  source_files:
    - src/tests
  requires:
    - pip
    - pytest-cov
  imports:
    - cyclonedx_py
  commands:
    - pip check
    - cyclonedx-bom --help
    - cyclonedx-py --help
    - pytest src/tests -vv --cov cyclonedx_py --cov-report term-missing:skip-covered --no-cov-on-fail -k "{{ test_skips }}" --cov-fail-under {{ cov_fail_under }}

about:
  home: https://github.com/CycloneDX/cyclonedx-python
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE

extra:
  recipe-maintainers:
    - bollwyvl
