{% set cov_fail_under = 63 %}
{% set test_skips = "not test_simple" %}
{% set version = "4.0.0" %}

package:
  name: cyclonedx-bom
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-bom/cyclonedx_bom-{{ version }}.tar.gz
    sha256: 937253800a416e5e40dda3c9f07247624b00fe6f9ea7d31c78a7f00585d054ab
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 9461552f4b4551f2e3f8f37ff48a8d915f6edf2f4a74f3f4e91622ccd73e99fd

build:
  number: 0
  noarch: python
  entry_points:
    - cyclonedx-bom = cyclonedx_py.client:main_deprecated
    - cyclonedx-py = cyclonedx_py.client:main
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - {{ PYTHON }} -c "import site, pathlib; sp = pathlib.Path(site.getsitepackages()[0]); [(sp / p).unlink() for p in ['LICENSE', 'NOTICE']]"

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - chardet >=5.0.0,<6.0.0
    - cyclonedx-python-lib >=2.0.0,<4.0.0
    - importlib-metadata >=3.4
    - packageurl-python >=0.9
    - pip-requirements-parser >=32.0.0,<33.0.0
    - python >=3.6
    - setuptools >=47.0.0
    - toml >=0.10.0,<0.11.0

test:
  {% set cov_fail_under = 63 %}
  {% set test_skips = "not test_simple" %}
  source_files:
    - src/tests
  requires:
    - ddt
    - pip
    - pytest-cov
  imports:
    - cyclonedx_py
  commands:
    - pip check
    - cyclonedx-bom --help
    - cyclonedx-py --help
    - cd src && pytest -vv --color=yes --tb=long --cov=cyclonedx_py --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k "{{ test_skips }}" --cov-fail-under={{ cov_fail_under }}

about:
  home: https://github.com/CycloneDX/cyclonedx-python
  summary: CycloneDX Software Bill of Materials (SBOM) generation utility
  license: Apache-2.0
  license_file:
    - dist/LICENSE
    - dist/NOTICE

extra:
  recipe-maintainers:
    - bollwyvl
